config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
  root 'home#index'
  resources :product, only: [:index, :show]
  resources :order, only: [:show, :destroy]
  resources :category
  # resources :order_item, only: [:create, :update, :destroy]
  resources :order_item
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  namespace :admin do 
    resources :categories
    resources :products, only: [:edit, :update, :show, :destroy]
    root 'categories#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :price, :discount, :description, :name, :category_id, :image, :trademark
  has_many :products, :dependent => :destroy
  validates :name_ct, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  def self.show
    Category.all
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [ :customer, :admin ]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user! ,:skiplayout, :new, :user_signed_in?, :is_admin?
  def index
   @categories = Category.all
  end

  def new
    @category = Category.new
  end
  def show
    category = Category.find_by_id params[:id]
    @products = category.products.paginate(page: params[:page], per_page: 1)
  end
  def create
    if category_params[:name_ct].blank? == true
      @category = Product.new(product_pamrams)
      if @category.save
       redirect_to admin_root_url
      else
        render :new
      end
    else
      @category = Category.new(category_params).products.new(product_pamrams)
      if @category.save
       redirect_to admin_root_url
      else
        render :new
      end
    end
  end

  def edit
  
  end

  def update
    
  end

  def destroy

  end

  private
    def category_params
      params.require(:category).permit(:name_ct)
    end

    def product_pamrams
      params.require(:category)
      .permit(:name, :price, :discount, :image, :description, :trademark, :category_id)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user! ,:skiplayout, :user_signed_in?, :is_admin?
   def edit
      @product = Product.find_by_id params[:id]
    end
    def update
      @product = Product.find_by_id params[:id]
      @product.update(product_pamrams)
      redirect_to admin_root_url
    end

    def show
      @product = Product.find_by_id params[:id]
    end

    def destroy
      @product = Product.find_by_id params[:id]
      @product.destroy
      respond_to do |format|
        format.html {redirect_to :back}
        format.json { head :no_content }
        format.js   { render layout: false }
      end
    end

    private
    def product_pamrams
      params.require(:product)
      .permit(:name, :price, :discount, :image, :description, :trademark, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order, :subtotal
  before_action :set_locale

  def skiplayout
    @skip_layout = true
  end

  def subtotal
    current_order.order_items.map{|k| k.product.price*k.quantity}.sum
  end

  def current_order
    if session[:order_id]
       Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def is_admin?
    if current_user.role.eql? 'admin'
    else
      redirect_to root_url
     end
  end
#  I18n
  #mac dinh trinh duyet se chi dinh chay ngon ngu nao
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
# function dung de khi minh dung scope trong routes
# thi khi chuyen trang van giu duoc trang thai cua ngon ngu dang chon
  def default_url_options
   { locale: I18n.locale }
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @products =  Category.find(params[:id]).products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.limit(8)
    @order_item = current_order.order_items.new
    @categories = Category.all
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

 def destroy
  @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
  respond_to do |format|
    format.html {}
    format.json { head :no_content }
    format.js   { render layout: false }
  end
end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
  def create
    @order = current_order
    if exists_product != true
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      flash[:danger] = 'Add to cart success!'
    else
      flash[:danger] = 'Product is exists in Your cart!'
    end
    session[:order_id] = @order.id
  end

  def update
    order_item_ids = params.keys.select{|key| key.include?('quantity')}
    order_items = current_order.order_items
    order_items.each_with_index do |value, index|
    value.update_attributes(quantity: params[order_item_ids[index]].to_i)
    end
    redirect_to :back
  end

  def destroy
    # byebug
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.permit(:quantity, :product_id)
  end

  def exists_product
    current_order.order_items.map{|oi| oi.product.id}.include?(params[:product_id].to_i)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @order_item = current_order.order_items.new
  end

  def show
     @product = Product.find_by_id params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'share/header' unless @skip_layout %>
    <%= yield %>
  <%= render 'share/footer' unless @skip_layout%> 
  </body>
</html>

app/views/share/_alert.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-success" id="alert-message">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
  <p><%= value %></p>
</div>
<% end %>
<%= yield %>

app/views/share/_btn_show_cart.html.erb
(<%= current_order.order_items.size.to_s %>)

app/views/share/_cart.html.erb
<%current_order.order_items.each do |oi| %>
  <span><%= oi.quantity %>x</span>&nbsp;
  <a href=""><%= oi.product.name %></a>
  <span style="margin-left: 6%"><%= number_to_currency oi.product.price * oi.quantity %>
    <%= link_to order_item_path(oi), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-trash" style="color: black"></span>
    <% end %>
  </span>
  <br>
<%end %>

app/views/share/_cart_text.html.erb
(<%= current_order.order_items.size %>)<%= t 'layout.header.item'%> <%= number_to_currency subtotal %>

app/views/share/_footer.html.erb
<div col-md-12>
<div class="text-center center-block"><br>
    <p class="txt-railway">ShoppingNOW.com</p>
    <br />
      <a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
      <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
      <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
      <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>
</div>

app/views/share/_header.html.erb
<nav class="navbar navbar-default" style="background-color: #23556C;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div style="margin-left: 24%">
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', :size => "50x50" %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style='margin-top: 1%'>
        
        <li><%= link_to t('layout.header.home'), root_path %></li>
        <li><%= link_to  t('layout.header.intro')%></li>
        <li><%= link_to  t( 'layout.header.news') %></li>
        <li><%= link_to  t('layout.header.guide') %></li>
        <li><%= link_to  t('layout.header.guide') %></li>
        <li><a href="#" class="glyphicon glyphicon-shopping-cart">  <span class="cart-text"><%= render 'share/cart_text' %></span></a></li> 
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Vi
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Vietnamese", locale:"vi" %></li>
          <li><%= link_to "English", locale:"en"%></li>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right"  style='margin-top: 1%'>
      <% if user_signed_in? == false %>
        <li>
        <%= link_to new_user_session_path do %>
          <i class="glyphicon glyphicon-user"></i> &nbsp;<%= t 'layout.header.login' %>
        <% end %>
        </li>
        <% else %>
          <li class="dropdown" >
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style='background-color: #23556C'><i class="glyphicon glyphicon-user"></i> &nbsp;<%= current_user.email %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" style='background-color: #23556C;border-radius: 15px'>
              <li><%= link_to 'Chỉnh sửa thông tin cá nhân',edit_user_registration_path %></li>
              <li><%= link_to 'Thoát',  destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/share/_side_bar.html.erb
<div class="col-md-4">
    <div class="col-md-12">
        <div class="row">
              <div class="col-sm-10 col-sm-offset-1">
                  <div id="imaginary_container"> 
                      <div class="input-group stylish-input-group">
                          <input type="text" class="form-control"  placeholder="Search" >
                          <span class="input-group-addon">
                              <button type="submit">
                                  <span class="glyphicon glyphicon-search"></span>
                              </button>  
                          </span>
                      </div>
                  </div>
              </div>
        </div>
    </div>
    <div class="col-md-12" > 
      <div class="li col-md-12">
        <%= t 'layout.sidebar.categories' %>
      </div>
      <div class="col-md-12">
        <li class="li_pr"><a href="">Business Phones</a></li>
        <li class="li_pr"><a href="">Fun Phones</a></li>
        <li class="li_pr"><a href="">Lifestyle Phones</a></li>
        <li class="li_pr"><a href="">Value Phones</a></li>
      </div>
    </div>
    <div class="col-md-12" > 
      <div class="li col-md-12">
       <%= t 'layout.sidebar.manufacturers' %>
      </div>
      <div class="col-md-12">
          <%Order.show.each do |t| %>
            <li class="li_pr"><%= link_to t.name_ct,category_path(t) %></li>
          <% end %>
      </div>
    </div>
    <div class="li col-md-12" ><%= t 'layout.sidebar.cart' %><button id="1" class="glyphicon glyphicon-chevron-down"></button> 
      <div id="123">
      <li class="li_pr2">
      <%= render 'share/cart' %>
      </li>
      </div>
      <li style="margin-left: 32px">
      <% if session[:order_id] %>
       <%= link_to order_path(current_order.id), class: ' btn btn-default' do %>
        Show Cart<span class="show_btn_cart"><%= render 'share/btn_show_cart' %></span>
       <% end %>
       <% else %>
       <button><%= t 'layout.sidebar.btn_cart' %><span class="show_btn_cart"><%= render 'share/btn_show_cart' %></span></button>
      <% end %>
      </li>
    </div>
    <div class="li col-md-12"> TAGS </div>
  </div>