config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
  root 'home#index'
  resources :product, only: [:index, :show]
  resources :order, only: [:show, :destroy]
  resources :category
  # resources :order_item, only: [:create, :update, :destroy]
  resources :order_item
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  namespace :admin do 
    resources :categories
    resources :products, only: [:edit, :update, :show, :destroy]
    root 'categories#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :price, :discount, :description, :name, :category_id, :image, :trademark
  has_many :products, :dependent => :destroy
  validates :name_ct, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  def self.show
    Category.all
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [ :customer, :admin ]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user! ,:skiplayout, :new, :user_signed_in?, :is_admin?
  def index
   @categories = Category.all
  end

  def new
    @category = Category.new
  end
  def show
    category = Category.find_by_id params[:id]
    @products = category.products.paginate(page: params[:page], per_page: 1)
  end
  def create
    if category_params[:name_ct].blank? == true
      @category = Product.new(product_pamrams)
      if @category.save
       redirect_to admin_root_url
      else
        render :new
      end
    else
      @category = Category.new(category_params).products.new(product_pamrams)
      if @category.save
       redirect_to admin_root_url
      else
        render :new
      end
    end
  end

  def edit
  
  end

  def update
    
  end

  def destroy

  end

  private
    def category_params
      params.require(:category).permit(:name_ct)
    end

    def product_pamrams
      params.require(:category)
      .permit(:name, :price, :discount, :image, :description, :trademark, :category_id)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user! ,:skiplayout, :user_signed_in?, :is_admin?
   def edit
      @product = Product.find_by_id params[:id]
    end
    def update
      @product = Product.find_by_id params[:id]
      @product.update(product_pamrams)
      redirect_to admin_root_url
    end

    def show
      @product = Product.find_by_id params[:id]
    end

    def destroy
      @product = Product.find_by_id params[:id]
      @product.destroy
      respond_to do |format|
        format.html {redirect_to :back}
        format.json { head :no_content }
        format.js   { render layout: false }
      end
    end

    private
    def product_pamrams
      params.require(:product)
      .permit(:name, :price, :discount, :image, :description, :trademark, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order, :subtotal
  before_action :set_locale

  def skiplayout
    @skip_layout = true
  end

  def subtotal
    current_order.order_items.map{|k| k.product.price*k.quantity}.sum
  end

  def current_order
    if session[:order_id]
       Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def is_admin?
    if current_user.role.eql? 'admin'
    else
      redirect_to root_url
     end
  end
#  I18n
  #mac dinh trinh duyet se chi dinh chay ngon ngu nao
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
# function dung de khi minh dung scope trong routes
# thi khi chuyen trang van giu duoc trang thai cua ngon ngu dang chon
  def default_url_options
   { locale: I18n.locale }
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @products =  Category.find(params[:id]).products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.limit(8)
    @order_item = current_order.order_items.new
    @categories = Category.all
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

 def destroy
  @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
  respond_to do |format|
    format.html {}
    format.json { head :no_content }
    format.js   { render layout: false }
  end
end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
  def create
    @order = current_order
    if exists_product != true
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      flash[:danger] = 'Add to cart success!'
    else
      flash[:danger] = 'Product is exists in Your cart!'
    end
    session[:order_id] = @order.id
  end

  def update
    order_item_ids = params.keys.select{|key| key.include?('quantity')}
    order_items = current_order.order_items
    order_items.each_with_index do |value, index|
    value.update_attributes(quantity: params[order_item_ids[index]].to_i)
    end
    redirect_to :back
  end

  def destroy
    # byebug
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.permit(:quantity, :product_id)
  end

  def exists_product
    current_order.order_items.map{|oi| oi.product.id}.include?(params[:product_id].to_i)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @order_item = current_order.order_items.new
  end

  def show
     @product = Product.find_by_id params[:id]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/categories/_form.html.erb
 <script>
    $(document).ready(function(){
      $("#show").click(function(){
          $("#sel1").hide();
          $("#ct").show();
      });
      $("#hide").click(function(){
          $("#sel1").show();
          $("#ct").hide();
      });
  });
 </script>
 <div class="col-md-4">
  <div class="col-md-10 col-md-offset-1" style="margin-top:22%; margin-bottom:22%"><img id="previewImage" style="width: 235px; height: 350px; border: 1px solid gray">
  </div>
</div>
<div class="col-md-8">
  <div class="col-md-12"><h2>Inforamtion Product:</h2></div>
  <div class="col-md-12" id="form_pr">
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <label for="usr">Name:</label>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Price:</label>
        <%= f.text_field :price, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Discout:</label>
        <%= f.text_field :discount, class: 'form-control'%>
      </div>
       <div class="form-group">
        <label for="pwd">Trademark:</label>
        <%= f.text_field :trademark, class: 'form-control'%>
      </div>
        <%= link_to "New Category","#",id: 'show', class: 'btn btn-danger', :remote =>true %>
        <%= link_to "Categories Exists","#", id: 'hide', class: 'btn btn-danger', :remote =>true %> 
      <div class="form-group" id="sel1" style="display: none;">
        <label for="pwd">Category:</label>
        <%= f.select :category_id, options_for_select(Category.all.map{|s|[s.name_ct, s.id]}), {}, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="pwd">Category:</label>
        <%= f.text_field :name_ct, class: 'form-control', id: 'ct'%>
      </div> 
      <div class="form-group">
        <label for="pwd">Image:</label>
        <%= f.file_field :image, onchange: 'loadImageFile(event)', class: 'form-control' %>
      </div>
      <div class="form-group"3
        <label for="comment">Comment:</label>
        <%= f.text_area :description, class: 'form-control'%>
      </div>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/categories/_show.html.erb
<div id="home" class="tab-pane fade in active">
  <div class="table-responsive">
      <table class="table product-table">
        <thead>
          <tr>
              <th></th>
              <th>Product</th>
              <th>Price</th>
              <th>Discout</th>
              <th>Trademark</th>
              <th>Description</th>
              <th></th>
          </tr>
        </thead>
        <tbody>
        <% @products.each do |pr| %>
          <tr>
              <th scope="row">
                  <%= image_tag pr.image.thumb.url%>
              </th>
              <td>
                  <h5><strong><%= pr.name %></strong></h5>
              </td>
              <td><%= pr.price %></td>
              <td><%= pr.discount %> %</td>
              <td>
                 <%= pr.trademark %>
              </td>
              <td><p style="color: black"><%= pr.description %></p></td>
              <td>
                  <%= link_to "X", admin_product_path(pr), method: :delete, remote: true, class: 'btn btn-sm btn-primary', id: 'destroy_pr'%>
                  <%= link_to "edit", edit_admin_product_path(pr), remote: true, class: 'btn btn-sm btn-primary'%>
                  <%= link_to "show", admin_product_path(pr.id), class: 'btn btn-sm btn-primary'%>
              </td>
          </tr>
        <% end %>
        <tr>
          </tr>
        </tbody>
        </table>
            <%= will_paginate @products %>
  </div>
</div>
<script>
$(function(){
   $('.pagination a').attr('data-remote', 'true')
});
</script>

app/views/admin/categories/edit.html.erb
 <script>
    $(document).ready(function(){
      $("#show").click(function(){
          $("#sel1").hide();
          $("#ct").show();
      });
      $("#hide").click(function(){
          $("#sel1").show();
          $("#ct").hide();
      });
  });
 </script>
 <div class="col-md-4">
  <div class="col-md-10 col-md-offset-1" style="margin-top:22%; margin-bottom:22%"><img id="previewImage" style="width: 235px; height: 350px; border: 1px solid gray">
  </div>
</div>
<div class="col-md-8">
  <div class="col-md-12"><h2>Inforamtion Product:</h2></div>
  <div class="col-md-12" id="form_pr">
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <label for="usr">Name:</label>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Price:</label>
        <%= f.text_field :price, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Discout:</label>
        <%= f.text_field :discount, class: 'form-control'%>
      </div>
       <div class="form-group">
        <label for="pwd">Trademark:</label>
        <%= f.text_field :trademark, class: 'form-control'%>
      </div>
        <%= link_to "New Category","#",id: 'show', class: 'btn btn-danger', :remote =>true %>
        <%= link_to "Categories Exists","#", id: 'hide', class: 'btn btn-danger', :remote =>true %> 
        <div class="form-group" id="sel1" style="display: none;">
        <label for="pwd">Category:</label>
        <%= f.select :category_id, options_for_select(Category.all.map{|s|[s.name_ct, s.id]}), {}, class: "form-control" %>
        </div>
        <div class="form-group">
        <label for="pwd">Category:</label>
        <%= f.text_field :name_ct, class: 'form-control', id: 'ct'%>
        <!-- <input type="text" class="form-control"> -->
      </div> 
      <div class="form-group">
        <label for="pwd">Image:</label>
        <%= f.file_field :image, onchange: 'loadImageFile(event)', class: 'form-control' %>
      </div>
      <div class="form-group"3
        <label for="comment">Comment:</label>
        <%= f.text_area :description, class: 'form-control'%>
      </div>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<body class="admin">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">PageAdmin</a>
      </div>
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown" style="margin-top: 8%;">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Chỉnh sửa thông tin cá nhân',edit_user_registration_path %></li>
          <li><%= link_to 'Thoát',  destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      </ul>
    </div>
  </nav>
  <div class="col-md-12">
    <div class="col-md-3">
    <div class="col-md-12" id='DashBoard'><h2>DashBoard</h2></div>
      <div class="li_cate_ad col-md-12">
        <ul>
          <li><a href="">QUAN LY HANG</a></li>
          <li><a href="">QUAN LY BOG</a></li>
          <li><a href="">QUAN LY KHACH HANG</a></li>
          <li><a href="">QUAN LY COMMENT</a></li>
          <li><a href="">THONG KE</a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-9" style="background-color: #fff;margin-left:-2%"><span class="glyphicon" style="color:#53B6F3">&#xe258;<a href="">Quan Ly Hang</a></span>
    <hr class="hr_ad">
    <!-- Tab control -->
    <div class="col-md-12" style="margin-left: -2%;">
      <ul class="nav nav-tabs">
      <% @categories.each do |ct|%>
        <li><a data-toggle="tab" href="#home<%= ct.id %>"><%= link_to ct.name_ct, admin_category_path(ct), remote: true %></a></li>
      <% end %>
      <li class="pull-right">
         <%= link_to '+', new_admin_category_path, remote: true, turbolinks: false , class: "btn btn-default"%>

      </li>
      </ul>
      <div class="tab-content">
        <div id="list-product"></div>
        </div>
      </div>
    </div>
    </div>
  </div>
</body>

app/views/admin/categories/new.js.erb
$("#list-product").html("<%= j render :partial => 'form' %>")

app/views/admin/categories/show.js.erb
$("#list-product").html("<%= j render :partial => 'show' %>")

app/views/admin/products/_form.html.erb
<div class="col-md-4">
  <div class="col-md-10 col-md-offset-1" style="margin-top:22%; margin-bottom:22%"><img id="previewImage" style="width: 235px; height: 350px; border: 1px solid gray">
  </div>
</div>
<div class="col-md-8">
  <div class="col-md-12"><h2>Inforamtion Product:</h2></div>
  <div class="col-md-12" id="form_pr">
    <%= form_for [:admin, @product] do |f| %>
      <div class="form-group">
        <label for="usr">Name:</label>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Price:</label>
        <%= f.text_field :price, class: 'form-control'%>
      </div>
      <div class="form-group">
        <label for="pwd">Discout:</label>
        <%= f.text_field :discount, class: 'form-control'%>
      </div>
       <div class="form-group">
        <label for="pwd">Trademark:</label>
        <%= f.text_field :trademark, class: 'form-control'%>
      </div>
      <div class="form-group" id="sel1">
       <label for="pwd">Category:</label>
       <%= f.select :category_id, options_for_select(Category.all.map{|s|[s.name_ct, s.id]}), {}, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="pwd">Image:</label>
        <%= f.file_field :image, onchange: 'loadImageFile(event)', class: 'form-control' %>
      </div>
      <div class="form-group"3
        <label for="comment">Comment:</label>
        <%= f.text_area :description, class: 'form-control'%>
      </div>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/products/_show.html.erb
<div id="home" class="tab-pane fade in active">
  <div class="table-responsive">
      <table class="table product-table">
        <thead>
          <tr>
              <th></th>
              <th>Product</th>
              <th>Price</th>
              <th>Discout</th>
              <th>Trademark</th>
              <th>Description</th>
              <th></th>
          </tr>
        </thead>
        <tbody>
        <% @products.each do |pr| %>
          <tr>
              <th scope="row">
                  <%= image_tag pr.image.thumb.url%>
              </th>
              <td>
                  <h5><strong><%= pr.name %></strong></h5>
              </td>
              <td><%= pr.price %></td>
              <td><%= pr.discount %> %</td>
              <td>
                 <%= pr.trademark %>
              </td>
              <td><p style="color: black"><%= pr.description %></p></td>
              <td>
                  <%= link_to "X", admin_category_path(pr), method: :delete, remote: true, class: 'btn btn-sm btn-primary', id: 'destroy_pr'%>
                  <%= link_to "edit", edit_admin_product_path(pr), remote: true, class: 'btn btn-sm btn-primary'%>
                  <%= link_to "show", admin_product_path(pr.id), class: 'btn btn-sm btn-primary'%>
              </td>
          </tr>
        <% end %>
        <tr>
            <td>PHAN TRANG</td>
          </tr>
        </tbody>
        </table>
  </div>
</div>

app/views/admin/products/destroy.js.erb
$('#destroy_pr').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/admin/products/edit.js.erb
$("#list-product").html("<%= j render :partial => 'form' %>")

app/views/admin/products/show.js.erb
$("#list-product").html("<%= j render :partial => 'show' %>")

app/views/category/show.html.erb
 <div class="col-md-10 col-md-offset-1" style="background-color: #fff;">
  <%= render 'share/side_bar' %>
  <div class="col-md-8">
  <br>
    <div class="col-xs-12"> <b><%= t 'home.view_product' %></b></div>
    <div class="col-xs-12">
      <hr>
      <div class="notice"><%= render 'share/alert', :flash => flash %></div>
      <hr>
    </div>
    <% @products.each do |product| %>
    <%= link_to product_path(product) do %>
      <div class="list_product col-xs-4">
        <div class="col-xs-12">
          <%= image_tag product.image.image_index.url%>
        </div>
        <div class="title_product col-xs-12">
          <a href=""><b><%= product.name %></b></a>
        </div>
        <div class="col-xs-12">
          <p class="description"><%= product.description %></p>
        </div>
        
        <div class="col-xs-12">
            <span style="color: #23556C; font-weight: bold;"><%= number_to_currency product.price %></span>
            <%= link_to t('home.add_cart'), order_item_index_path(quantity: 1, product_id: product.id), method: :post, remote: true,class: 'btn btn-default pull-right' %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

app/views/home/index.html.erb
 <div class="col-md-10 col-md-offset-1" style="background-color: #fff;">
  <%= render 'share/side_bar' %>
  <div class="col-md-8">
    <div class="col-md-12">
      <div class="col-xs-5" style="background-color: #fff;">
       <%= image_tag 'product1.png', :size => "191x320" %>
      </div>
      <div class="col-xs-7">
        <div class="col-md-12">
          <h2>IPHONE 4.</h2>
        </div>
        <div class="col-md-12">
          <p>What is Lorem Ipsum?
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
        </div>
        <div class="col-md-12">
          <button class="btn btn-primary pull-right"><%= t 'home.btn_show' %></button>
        </div>
      </div>
    </div>
     <div class="col-md-12" >
      <br>
      <hr class="style15">
      <br>
    </div>

    <div class="col-xs-12">
    <b><%= t 'home.featured_product' %></b>      
    </div>
    <div class="col-xs-12">
      <hr>
      <div class="notice"><%= render 'share/alert', :flash => flash %></div>
      <hr>
    </div>
    <div class="col-xs-12"> 
    <% @products.each do |product| %>
    <%= link_to product_path(product) do %>
      <div class="list_product col-xs-3">
        <div class="col-xs-12">
          <%= image_tag product.image.image_index.url%>
        </div>
        <div class="title_product col-xs-12">
          <a href=""><b><%= product.name %></b></a>
        </div>
        <div class="col-xs-12">
          <p class="description"><%= product.description %></p>
        </div>
        
        <div class="col-xs-12">
            <span style="color: #23556C; font-weight: bold;"><%= number_to_currency product.price %></span>
            <%= link_to t('home.add_cart'), order_item_index_path(quantity: 1, product_id: product.id), method: :post, remote: true,class: 'btn btn-default pull-right' %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/order/destroy.js.erb
$('.destroy-product').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")

app/views/order/show.html.erb
 <div class="col-md-10 col-md-offset-1" style="background-color: #fff;">
  <%= render 'share/side_bar' %>
  <div class="col-md-8">
    <div class="col-xs-12">
      <hr>
      <div class="notice"><%= render 'share/alert', :flash => flash %></div>
      <hr>
    </div>
    <div class="col-md-12">
      <span style="color:#EFEEEA"><b>Home>Your shopping cart</b></span>
    </div>
     <div class="col-md-12" >
      <br>
      <hr class="style15">
      <br>
    </div>
          <!--Shopping Cart table-->
      <div class="table-responsive">
          <table class="table product-table">
              <!--Table head-->
              <thead>
                <tr>
                  <th></th>
                  <th>Product</th>
                  <th>Price</th>
                  <th>Discout</th>
                  <th>Trademark</th>
                  <th>Quantity</th>
                  <th>Amount</th>
                  <th></th>
               </tr>
              </thead>
              <%= form_tag(order_item_path, method: :patch) do %>
              <tbody>
              <% @order_items.each do |oi| %>
                <tr>
                    <th scope="row">
                        <%= image_tag oi.product.image.thumb.url %>
                    </th>
                    <td>
                        <h5><strong><%= oi.product.name %></strong></h5>
                        <p class="text-muted">by Admin</p>
                    </td>
                    <td id="price-<%= oi.product.id %>"><%= oi.product.price %></td>
                    <td><%=number_to_currency oi.product.discount %></td>
                    <td><%= oi.product.trademark %></td>
                    <td>
                        <%= text_field_tag "quantity-#{oi.product.id}", oi.quantity, {id: "quantity-#{oi.product.id}", class: "form-control", style: "width: 44%"} %>
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-sm btn-primary btn-rounded" onclick="tru(<%=oi.product.id%>)">
                                <input type="radio" name="options" id="option1">&mdash;
                            </label>
                            <label class="btn btn-sm btn-primary btn-rounded" onclick="cong(<%=oi.product.id%>)">
                                <input type="radio" name="options" id="option1">+
                            </label>
                        </div>
                    </td>
                    <td id="amount-<%= oi.product.id %>"><%= number_to_currency oi.product.price * oi.quantity %></td>
                    <td>
                        <%= link_to order_path(oi), method: :delete, remote: true, class: "destroy-product" do %>
                            <span class="glyphicon glyphicon-trash" style="color: black"></span>
                        <% end %>
                    </td>
                </tr>
                <% end %>
                
                <tr>
                    <td colspan="3"></td>
                    <td>
                        <h4><strong>Total</strong></h4></td>
                    <td>
                        <h4><strong> <%= number_to_currency subtotal %></strong></h4></td>
                    <td colspan="3"><button type="button" class="btn btn-primary">PAYMENT</button>
                    <%= submit_tag "UPDATE CART", class: 'btn btn-danger btn-md pull-right' %>
                    </td>
                </tr>
              </tbody>
              <% end %>
          </table>
      </div>
  </div>

app/views/order_item/create.js.erb
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".notice").html("<%= escape_javascript(render 'share/alert') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")

app/views/order_item/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'share/cart_text') %>")
$(".li_pr2").html("<%= escape_javascript(render 'share/cart') %>")
$(".show_btn_cart").html("<%= escape_javascript(render 'share/btn_show_cart') %>")

app/views/product/show.html.erb
 <div class="col-md-10 col-md-offset-1" style="background-color: #fff;">
  <%= render 'share/side_bar' %>
  <div class="col-md-8">
    <div class="col-xs-12">
      <hr>
      <div class="notice"><%= render 'share/alert', :flash => flash %></div>
      <hr>
    </div>
    <div class="col-xs-12"> <h4><b>Details</b></h4></div>
    <div class="col-md-12">
      <div class="col-xs-5" style="background-color: #fff;">
       <%= image_tag @product.image.image_show.url%>
      </div>
      <div class="col-xs-7">
        <div class="col-md-12">
          <h2><%= @product.name %></h2>
        </div>
        <div class="col-md-12">
          <p>What is Lorem Ipsum?
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
        </div>
        <div class="col-md-12">
          <a href="#home" class="btn btn-primary pull-right">More details</a>
        </div>
        <div class="col-md-12">
          <span style="color: #23556C; font-weight: bold;"><h5><%= @product.name %>:</h5></span>
        </div>
        <div class="col-md-12">
          <span style="color: #23556C; font-weight: bold;">Price:</span><i><%= number_to_currency @product.price %>-tax incl.</i>
        </div>
        <div class="col-md-12">
        <%= link_to 'Add to cart', order_item_index_path(quantity: 1, product_id: @product.id), method: :post, remote: true,class: 'btn btn-default pull-right' %>
        </div>
      </div>
    </div>
     <div class="col-md-12" >
      <br>
      <hr class="style15">
      <br>
    </div>
    <div class="col-xs-12">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">MORE INFO</a></li>
        <li><a data-toggle="tab" href="#menu1">DATA SHEET</a></li>
        <li><a data-toggle="tab" href="#menu1">FEEDBACK</a></li>
      </ul>
      <div class="tab-content"  style="border: 1px solid #EFEEEA">
        <div id="home" class="tab-pane fade in active">
          <p><%= @product.description %></p>
        </div>
        <div id="menu1" class="tab-pane fade">
          <h3>Menu 1</h3>
          <p>Some content in menu 1.</p>
        </div>
      </div>
    </div>
  </div>
</div>